import{type ButtonHTMLAttributes,type HTMLAttributes,type InputHTMLAttributes,type ReactNode,type SelectHTMLAttributes,type TextareaHTMLAttributes,useId,useState}from"react";
import{clampPercent,cx,initials,type AcmeTone,type AcmeVariant}from"@acmeui/core";
export type ButtonProps=ButtonHTMLAttributes<HTMLButtonElement>&{variant?:AcmeVariant;loading?:boolean};
export function Button({variant="primary",loading=false,className,children,disabled,...props}:ButtonProps){return <button className={cx("acme-button",`acme-button--${variant}`,className)} disabled={disabled||loading}{...props}>{loading?"載入中…":children}</button>}
export function Card({className,...props}:HTMLAttributes<HTMLDivElement>){return <section className={cx("acme-card",className)}{...props}/>}
export function CardHeader({className,...props}:HTMLAttributes<HTMLDivElement>){return <header className={cx("acme-card__header",className)}{...props}/>}
export function CardContent({className,...props}:HTMLAttributes<HTMLDivElement>){return <div className={cx("acme-card__content",className)}{...props}/>}
export function CardFooter({className,...props}:HTMLAttributes<HTMLDivElement>){return <footer className={cx("acme-card__footer",className)}{...props}/>}
export function Badge({className,...props}:HTMLAttributes<HTMLSpanElement>){return <span className={cx("acme-badge",className)}{...props}/>}
export function Field({label,help,htmlFor,children}:{label:string;help?:string;htmlFor?:string;children:ReactNode}){return <label className="acme-field" htmlFor={htmlFor}><span className="acme-label">{label}</span>{children}{help?<span className="acme-help">{help}</span>:null}</label>}
export const Input=({className,...props}:InputHTMLAttributes<HTMLInputElement>)=><input className={cx("acme-input",className)}{...props}/>;
export const Textarea=({className,...props}:TextareaHTMLAttributes<HTMLTextAreaElement>)=><textarea className={cx("acme-textarea",className)}{...props}/>;
export const Select=({className,...props}:SelectHTMLAttributes<HTMLSelectElement>)=><select className={cx("acme-select",className)}{...props}/>;
export function Checkbox({label,...props}:InputHTMLAttributes<HTMLInputElement>&{label:string}){return <label className="acme-checkbox"><input type="checkbox"{...props}/><span>{label}</span></label>}
export function Switch({checked,defaultChecked,onCheckedChange,label="切換"}:{checked?:boolean;defaultChecked?:boolean;onCheckedChange?:(v:boolean)=>void;label?:string}){const[state,setState]=useState(Boolean(defaultChecked));const current=checked??state;const toggle=()=>{const next=!current;if(checked===undefined)setState(next);onCheckedChange?.(next)};return <button type="button" role="switch" aria-checked={current} aria-label={label} data-checked={String(current)} className="acme-switch" onClick={toggle}/>}
export function Alert({tone="info",title,children}:{tone?:AcmeTone;title:string;children?:ReactNode}){return <div role="alert" className={cx("acme-alert",tone!=="info"&&`acme-alert--${tone}`)}><strong>{title}</strong>{children?<div>{children}</div>:null}</div>}
export function Progress({value,label="進度"}:{value:number;label?:string}){const safe=clampPercent(value);return <div className="acme-progress" role="progressbar" aria-label={label} aria-valuemin={0} aria-valuemax={100} aria-valuenow={safe}><div className="acme-progress__bar" style={{width:`${safe}%`}}/></div>}
export function Avatar({src,name,className}:{src?:string;name:string;className?:string}){return <span className={cx("acme-avatar",className)}>{src?<img src={src} alt={name}/>:initials(name)}</span>}
export function Tabs({items,defaultValue}:{items:Array<{value:string;label:string;content:ReactNode}>;defaultValue?:string}){const[active,setActive]=useState(defaultValue??items[0]?.value);return <div className="acme-tabs"><div className="acme-tabs__list" role="tablist">{items.map(i=><button key={i.value} type="button" role="tab" className="acme-tabs__trigger" aria-selected={active===i.value} onClick={()=>setActive(i.value)}>{i.label}</button>)}</div>{items.map(i=>active===i.value?<div key={i.value} role="tabpanel" style={{padding:"1rem 0"}}>{i.content}</div>:null)}</div>}
export function Modal({open,title,children,onClose}:{open:boolean;title:string;children:ReactNode;onClose:()=>void}){const id=useId();if(!open)return null;return <div className="acme-modal" role="presentation" onMouseDown={e=>{if(e.currentTarget===e.target)onClose()}}><section className="acme-modal__panel" role="dialog" aria-modal="true" aria-labelledby={id}><div className="acme-cluster" style={{justifyContent:"space-between"}}><h2 id={id}>{title}</h2><Button variant="ghost" onClick={onClose} aria-label="關閉">×</Button></div>{children}</section></div>}
export type DataTableColumn<T>={key:keyof T;label:string;render?:(value:T[keyof T],row:T)=>ReactNode};
export function DataTable<T extends Record<string,unknown>>({columns,rows,caption}:{columns:Array<DataTableColumn<T>>;rows:T[];caption?:string}){return <div className="acme-table-wrap"><table className="acme-table">{caption?<caption>{caption}</caption>:null}<thead><tr>{columns.map(c=><th key={String(c.key)}>{c.label}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{columns.map(c=><td key={String(c.key)}>{c.render?c.render(r[c.key],r):String(r[c.key]??"")}</td>)}</tr>)}</tbody></table></div>}
export function Breadcrumb({items}:{items:Array<{label:string;href?:string}>}){return <nav aria-label="麵包屑" className="acme-breadcrumb">{items.map((i,n)=><span key={i.label}>{n>0?" / ":null}{i.href?<a href={i.href}>{i.label}</a>:i.label}</span>)}</nav>}
export function Pagination({page,totalPages,onPageChange}:{page:number;totalPages:number;onPageChange:(p:number)=>void}){const pages=Array.from({length:Math.min(totalPages,7)},(_,i)=>i+1);return <nav className="acme-pagination" aria-label="分頁"><button onClick={()=>onPageChange(Math.max(1,page-1))} disabled={page===1}>‹</button>{pages.map(p=><button key={p} aria-current={p===page?"page":undefined} onClick={()=>onPageChange(p)}>{p}</button>)}<button onClick={()=>onPageChange(Math.min(totalPages,page+1))} disabled={page===totalPages}>›</button></nav>}
export function Navbar({brand,links,action}:{brand:ReactNode;links:Array<{label:string;href:string}>;action?:ReactNode}){return <header className="acme-navbar"><div className="acme-container acme-navbar__inner"><strong>{brand}</strong><nav className="acme-navbar__links">{links.map(l=><a key={l.href} href={l.href}>{l.label}</a>)}</nav>{action}</div></header>}
export function Sidebar({items}:{items:Array<{label:string;href:string;active?:boolean}>}){return <aside className="acme-sidebar"><nav className="acme-stack">{items.map(i=><a key={i.href} href={i.href} aria-current={i.active?"page":undefined}>{i.label}</a>)}</nav></aside>}
export function Hero({title,description,actions,visual}:{title:string;description:string;actions?:ReactNode;visual?:ReactNode}){return <section className="acme-hero"><div className="acme-container acme-hero__grid"><div><h1>{title}</h1><p>{description}</p><div className="acme-cluster">{actions}</div></div>{visual?<div>{visual}</div>:null}</div></section>}
export function FeatureGrid({items}:{items:Array<{title:string;description:string;icon?:ReactNode}>}){return <div className="acme-feature-grid">{items.map(i=><article className="acme-feature" key={i.title}>{i.icon}<h3>{i.title}</h3><p>{i.description}</p></article>)}</div>}
export function PricingTable({plans}:{plans:Array<{name:string;price:string;description:string;features:string[];featured?:boolean}>}){return <div className="acme-pricing">{plans.map(p=><article className={cx("acme-price",p.featured&&"acme-price--featured")} key={p.name}><h3>{p.name}</h3><div style={{fontSize:"2.25rem",fontWeight:800}}>{p.price}</div><p>{p.description}</p><ul>{p.features.map(f=><li key={f}>{f}</li>)}</ul><Button variant={p.featured?"primary":"outline"}>選擇方案</Button></article>)}</div>}
export function Footer({brand,columns}:{brand:string;columns:Array<{title:string;links:Array<{label:string;href:string}>}>}){return <footer className="acme-footer"><div className="acme-container acme-grid"><div><strong>{brand}</strong><p>Semantic-first, multi-framework UI.</p></div>{columns.map(c=><div key={c.title}><strong>{c.title}</strong>{c.links.map(l=><div key={l.href}><a href={l.href}>{l.label}</a></div>)}</div>)}</div></footer>}
